on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Build My Apps

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter pub get

      - name: Install FlutterFire CLI
        run: dart pub global activate flutterfire_cli

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Configure Firebase
        run: flutterfire configure --project=systembeta-7881e --platforms=android

      - run: flutter build apk --release

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          tag: v${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
